# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-04 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('avatar', models.ImageField(blank=True, upload_to='avatar/')),
                ('external_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
